#!/usr/bin/env python3
"""Generates kernel/net/ca_store.c: the built-in trust anchors.

Source: the system CA bundle (Mozilla roots as packaged by the distribution).
Selection: RSA keys of 2048..4096 bits whose modulus length is a multiple of 32
bits (all that kernel/net/rsa.c can use), not yet expired. ECDSA roots are left
out because the kernel cannot verify ECDSA signatures anyway.

usage: gen_ca_store.py [BUNDLE.crt] > kernel/net/ca_store.c
"""
import subprocess, sys, re, datetime, base64, hashlib
bundle = sys.argv[1] if len(sys.argv) > 1 else "/etc/ssl/certs/ca-certificates.crt"
pem = open(bundle).read()
blocks = re.findall(r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----", pem, re.S)
now = datetime.datetime.utcnow()
def openssl(args, inp):
    return subprocess.run(["openssl"] + args, input=inp, capture_output=True, text=True).stdout
roots = []
for b in blocks:
    txt = openssl(["x509", "-noout", "-subject", "-enddate", "-text", "-nameopt", "RFC2253"], b)
    m = re.search(r"Public Key Algorithm: rsaEncryption\s+Public-Key: \((\d+) bit\)", txt)
    if not m: continue
    bits = int(m.group(1))
    if bits < 2048 or bits > 4096 or bits % 32: continue
    end = re.search(r"notAfter=(.*)", txt).group(1).strip()
    end_dt = datetime.datetime.strptime(end, "%b %d %H:%M:%S %Y %Z")
    if end_dt <= now + datetime.timedelta(days=30): continue
    subj = re.search(r"subject=(.*)", txt).group(1).strip()
    cn = re.search(r"CN=([^,]+)", subj)
    org = re.search(r"O=([^,]+)", subj)
    name = (cn.group(1) if cn else (org.group(1) if org else subj))
    name = re.sub(r"\\([0-9A-Fa-f]{2})", "?", name).replace("\\", "")      # RFC 2253 escapes -> plain ASCII
    der = base64.b64decode("".join(b.strip().splitlines()[1:-1]))
    roots.append((name, bits, end_dt, der))
roots.sort(key=lambda r: (r[0].lower(), r[3]))
seen = set(); uniq = []
for r in roots:
    h = hashlib.sha256(r[3]).hexdigest()
    if h in seen: continue
    seen.add(h); uniq.append(r)
roots = uniq
print("/* GENERATED by tools/net-test/gen_ca_store.py -- do not edit by hand.")
print(" *")
print(" * Built-in trust anchors: %d RSA root certificates from the Mozilla CA list as" % len(roots))
print(" * packaged by the build host's ca-certificates (snapshot %s)." % now.strftime("%Y-%m-%d"))
print(" * Roots are trusted by identity (their own signature is not evaluated), so a")
print(" * root that is removed from the Mozilla list later stays trusted here until")
print(" * this file is regenerated. Extra roots can be added at run time with")
print(" * x509_trust_add() (shell: tls trust FILE). */")
print('#include "x509.h"')
print()
for i, (name, bits, end, der) in enumerate(roots):
    print("/* %s, RSA-%d, expires %s */" % (name.replace("*/", "* /"), bits, end.strftime("%Y-%m-%d")))
    print("static const uint8_t ca_%03d[%d] = {" % (i, len(der)))
    for o in range(0, len(der), 16):
        print("    " + ",".join("0x%02x" % x for x in der[o:o+16]) + ",")
    print("};")
print()
print("const x509_der_t ca_store_builtin[%d] = {" % max(len(roots), 1))
for i, (_, _, _, der) in enumerate(roots):
    print("    { ca_%03d, %d }," % (i, len(der)))
print("};")
print("const int ca_store_builtin_count = %d;" % len(roots))
